baseurl = "https://jwallblog.netlify.com/"
languageCode = "en-us"
title = "Wallace's DS Blog"
# Define how many pages appear per site
paginate = 10
disqusShortname = "spf13"
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Wallace"
    site_description = "What I do on MWF in the Morning"
    location = "Mercyhurst"
    # Link custom assets relative to /static
    avatar = "img/cheetos.png"
    header_background = "img/palms2.jpg"
    header_title = "MY DS CHEETO BLOG"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []



[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    github    = "JWall7"
   
